#!/usr/bin/env python
import dbus
import sys
import os

try:
    # Try and set skype window to normal
    remote_bus = dbus.SessionBus()
    out_connection = remote_bus.get_object('com.Skype.API', '/com/Skype')
    out_connection.Invoke('NAME mySkypeController')
    out_connection.Invoke('PROTOCOL 5')
    #out_connection.Invoke('SET WINDOWSTATE MAXIMIZED')
    out_connection.Invoke('SET WINDOWSTATE NORMAL')
    out_connection.Invoke('FOCUS')

    # 'FOCUS' does not reliably raise the window or give it keyboard focus :-(
    if os.system('which wmctrl') == 0:
        os.system(u'wmctrl -a Skype\N{TRADE MARK SIGN}'.encode('utf-8'))
    else:
        # Fallback: This only partially raises and doesn't seem to focus.
        # It does draw attention to where the covered window is.
        out_connection.Invoke('SET WINDOWSTATE HIDDEN')
        out_connection.Invoke('SET WINDOWSTATE NORMAL')

except:
    os.system('skype')
    sys.exit()
