#!/usr/bin/env python
import dbus
import subprocess
import sys
import time

MAX_SECONDS_WAITING_TO_APPEAR = 5

try:
    # Try and set skype window to normal
    remote_bus = dbus.SessionBus()
    out_connection = remote_bus.get_object('com.Skype.API', '/com/Skype')
    out_connection.Invoke('NAME mySkypeController')
    out_connection.Invoke('PROTOCOL 5')
    #out_connection.Invoke('SET WINDOWSTATE MAXIMIZED')
    out_connection.Invoke('SET WINDOWSTATE NORMAL')
    out_connection.Invoke('FOCUS')

    # 'FOCUS' does not reliably raise the window or give it keyboard focus :-(
    if subprocess.call(['which', 'wmctrl'], stdout=subprocess.PIPE) == 0:
        skype_title_pattern = u'Skype\N{TRADE MARK SIGN}'.encode('utf-8')
        t0 = time.time()
        while (skype_title_pattern not in
               subprocess.check_output(['wmctrl', '-l'])
               and
               time.time() < t0 + MAX_SECONDS_WAITING_TO_APPEAR):
            time.sleep(0.25)
        subprocess.check_call(['wmctrl', '-a', skype_title_pattern])
    else:
        # Fallback: This only partially raises and doesn't seem to focus.
        # It does draw attention to where the covered window is.
        out_connection.Invoke('SET WINDOWSTATE HIDDEN')
        out_connection.Invoke('SET WINDOWSTATE NORMAL')

except:
    subprocess.call(['skype'])
    sys.exit()
